# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('unprocessed_doc', models.FileField(null=True, upload_to=b'')),
                ('processed_doc', models.FileField(blank=True, null=True, upload_to=b'')),
                ('generated_questions_doc', models.FileField(null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_question', models.CharField(max_length=120)),
                ('score', models.FloatField(default=3.5)),
                ('acceptable', models.BooleanField(default=False)),
                ('correct_answer', models.CharField(max_length=30)),
                ('option1', models.CharField(max_length=30)),
                ('option2', models.CharField(max_length=30)),
                ('option3', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
