# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20170517_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='generated_questions_doc',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
