# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20170517_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='final_question',
            new_name='question',
        ),
        migrations.AddField(
            model_name='document',
            name='file_extension',
            field=models.CharField(choices=[(b'.srt', b'Closed Caption File'), (b'.txt', b'Text File')], default=b'.txt', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='json_doc',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='question',
            name='Edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='generation_medium',
            field=models.CharField(choices=[(b'Automated', b'Automated'), (b'Manually', b'Manually')], default=b'Automated', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='unprocessed_doc',
            field=models.FileField(null=True, upload_to=documents.models.upload_location_unprocessed_file),
        ),
    ]
