# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20170520_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Edited',
            new_name='edited',
        ),
    ]
