# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20170521_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sentence',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
