# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_question_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default=b'Yes', max_length=30),
        ),
    ]
