# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20170521_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
