# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_question_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[(b'mcq', b'Multiple Choice'), (b'reason', b'Reasoning')], default=b'mcq', max_length=15, null=True),
        ),
    ]
