# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='skippable',
            field=models.BooleanField(default=True),
        ),
    ]
