# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_question_skippable'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
