# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20170522_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='generation_medium',
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[(b'Auto', b'Automated'), (b'Man', b'Manually')], default=b'Auto', max_length=1, null=True),
        ),
    ]
