# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20170528_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[(b'Automated', b'Automated'), (b'Manually', b'Manually')], default=b'Automated', max_length=1, null=True),
        ),
    ]
