# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_auto_20170528_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_as_source',
            field=models.BooleanField(default=True),
        ),
    ]
