# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_document_file_as_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_extension',
            field=models.CharField(choices=[('.srt', 'Closed Caption File'), ('.txt', 'Text File')], default='.txt', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='generated_questions_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='json_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='Yes', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('Automated', 'Automated'), ('Manually', 'Manually')], default='Automated', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('reason', 'Reasoning')], default='mcq', max_length=15, null=True),
        ),
    ]
