# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_auto_20170620_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='file_as_source',
            new_name='file_as_input',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='unprocessed_doc',
            new_name='input_file',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='json_doc',
            new_name='json_out_file',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='processed_doc',
            new_name='processed_file',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='generated_questions_doc',
            new_name='questions_file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_extension',
        ),
        migrations.RemoveField(
            model_name='question',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated',
        ),
        migrations.AddField(
            model_name='document',
            name='format',
            field=models.CharField(choices=[('.json', 'Json Format'), ('.txt', 'Text Format')], default='.txt', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='No-Title', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='sentence',
            field=models.CharField(default=django.utils.timezone.now, max_length=160),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('auto', 'Automated'), ('man', 'Manual')], default='auto', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), null=True),
        ),
    ]
